parameters:
  # Required. Service connection to use to get to the keyvault
  - name: azure_subscription
    type: string

  # Required. name of keyvault to use to retrieve secrets from.
  # in vault you should have
  # Publish to forge: forgeToken
  # Publish to confluence: confluenceNPAUsername, confluenceNPAPassword
  - name: key_vault_name
    type: string

  # Optional
  - name: do_mongodbimport
    type: boolean
    default: false

  # Optional
  - name: uri
    type: string
    default: $(mongodb-uri)

  # Optional
  - name: database_name
    type: string
    default: quale-db

  # Optional
  - name: collection_name
    type: string
    default: tool-collection

  # Optional
  - name: json_file_path
    type: string
    default: $(System.DefaultWorkingDirectory)/issues.csv.json

stages:
  - stage: openrewrite
    displayName: OpenRewrite recipes

    jobs:
      - job: apply_our_recipes
        displayName: Apply our recipes
        pool:
          vmImage: 'ubuntu-20.04'

        steps:
          - task: Bash@3
            inputs:
              script: |
                ./gradlew publishToMavenLocal
            displayName: 'Publish recipes to maven local'

          - task: Bash@3
              inputs:
                script: |
                  if [ -f "build.gradle.kts"]; then
                    echo "todo: Add to plugins: "
                    echo "id("org.openrewrite.rewrite") version("5.14.0")"
                    echo "todo: Adding dependency to gradle"
                    # In dependencies block: add:
                    echo 'rewrite("nl.kevinvandervlist.recipes:company-recipes:0.0.1")'
                    echo "todo: Activating recipe"
                    # Add a new block:
                    echo -e "rewrite { \n  activeRecipe("nl.kevinvandervlist.RecipeCollection") \n}"
                  fi
              displayName: 'Publish recipes to maven local'

          - task: Bash@3
            inputs:
              script: |
                ./gradlew --no-daemon rewriteDryRun
            displayName: 'Create patch'
