stages:
  - stage: openrewrite
    displayName: OpenRewrite recipes

    jobs:
      - job: apply_our_recipes
        displayName: Apply our recipes
        pool:
          vmImage: 'ubuntu-20.04'

        steps:
          - task: Bash@3
            inputs:
              script: |
                ./gradlew publishToMavenLocal
            displayName: 'Publish recipes to maven local'

          - task: Bash@3
            inputs:
              script: |
                if [ -f "build.gradle.kts"]; then
                  ./gradlew --no-daemon rewriteDryRun
                fi
                if [ -f "pom.xml"]; then
                  mvn rewrite:dryRun
                fi
            displayName: 'Create patch'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: "/target/site/rewrite/rewrite.patch"
              artifactName: OpenRewritePatch